name: Payment System CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DATABASE_URL_TEST: postgres://postgres@localhost:5432/payment_system_test
  REDIS_URL: redis://localhost:6379
  JWT_SECRET: jwt_secret_32_chars_min
  OTP_SECRET: otp_secret_16_chars_min

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: payment_system_test
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install PostgreSQL Client
      run: sudo apt-get install -y postgresql-client

    - name: Setup Test Database
      run: |
        psql -h localhost -U postgres -d payment_system_test -c "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";"
        psql -h localhost -U postgres -d payment_system_test -f migrations/001_*.sql

    # Core Tests
    - name: Run Unit Tests
      run: cargo test --test unit -- --test-threads=1

    - name: Run Integration Tests
      run: cargo test --test integration -- --test-threads=1

    - name: Run Security Tests
      run: cargo test --test security

    - name: Run Property Tests
      run: cargo test --test property

    - name: Run Chaos Tests
      run: cargo test --test chaos

    - name: Run Contract Tests
      run: cargo test --test contract

    # Advanced Testing
    - name: Run Mutation Tests
      run: |
        cargo install cargo-mutants
        cargo mutants --package payment_system --path src/wallet -- --test-threads=1 --caught
        cargo mutants --package payment_system --path src/payment -- --test-threads=1 --caught

    - name: Run Tracing Tests
      run: cargo test --test tracing

    - name: Run Canary Deployment Tests
      run: cargo test --test canary

    - name: Run Blue-Green Deployment Tests
      run: cargo test --test deployment

    # Security Scanning
    - name: Security Audit
      run: |
        cargo install cargo-audit
        cargo audit

    - name: License & Dependency Compliance
      run: |
        cargo install cargo-deny
        cargo deny check

    # Performance
    - name: Run Benchmarks
      run: cargo bench

    # Build
    - name: Build Release
      run: cargo build --release

    # Container Scan (if Dockerized)
    - name: Container Security Scan
      if: always()
      run: |
        docker build -t payment-system:latest .
        trivy image --exit-code 1 --severity CRITICAL payment-system:latest